### ISSUE TITLE
datapack validation fail on 1.18.2

### ISSUE THREAD

**Issue by coaber** [LunarEclipseStudios/From-The-Fog#9]
it seems the pack does not work properly on 1.18.2, log shows unbound values in the resource key registry, which means the way the structure features are defined in the file uses 1.19.X changes. is it possible that those tweaks be made so the pack works on 1.18 as well? Apparently it is the only thing that keeps it from working correctly. launching it manually after you enter the world works as intended (as in almost all the features work), as soon as you reboot the world, it will fail to launch with the pack enabled due to the structures.
